name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: sudo apt install -y libsdl2-dev libsdl2-ttf-dev

    - name: test build
      run: ./build.sh -Wall
