name: test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
        sudo apt update
        sudo apt install -y libsdl2-dev libsdl2-ttf-dev libgifwrap-dev
    
    - name: install gifwrap
      run: |
        git clone https://github.com/aouwt/SDL_gifwrap.git
        cd SDL_gifwrap
        make
        sudo make install
        cd ..

    - name: test build
      run: make
